#!/usr/bin/env python
import csha
import sys

if len(sys.argv) == 2:

    sf = csha.Statefile()

    if sys.argv[1] == "init":
        csha.log.debug('HA ha_set_pool_state init')
        sf.set_master(csha.Master(None, None))
        sf.format_all_hosts()
        sf.set_invalid(False)

    elif sys.argv[1] == "invalid":
        sf.set_invalid(True)
        csha.log.debug('HA ha_set_pool_state invalid')
