#!/usr/bin/env python
import csha

csha.log.debug('HA ha_start_daemon')

nodeid = csha.get_current_host_node_id()
my_host_uuid = csha.util.get_current_host_uuid()

sf = csha.Statefile()
sf.set_host(nodeid, csha.Host(my_host_uuid, True))
