#!/usr/bin/env python
import os
import csha
import signal

csha.log.debug('HA ha_stop_daemon')

nodeid = csha.get_current_host_node_id()
my_host_uuid = csha.util.get_current_host_uuid()

sf = csha.Statefile()

master = sf.get_master()
if master.uuid == my_host_uuid:
    try:
        os.kill(master.pid, signal.SIGTERM)
    except:
        csha.log.debug('HA ha_stop_daemon failed to kill master lock process')
    sf.set_master(csha.Master(None, None))
